// =================================================================================================
// IMPORTS
// =================================================================================================

require('dotenv').config()
const logger = require('morgan')
const express = require('express')
const Account = require('./account')
const passport = require('passport')
const flash = require('express-flash')
const session = require('express-session')
const ensureLoggedIn = require('connect-ensure-login').ensureLoggedIn

// =================================================================================================
// INITIALIZATIONS
// =================================================================================================



const TIMEOUT_HOURS = 8 // Number of hours before a login session expires
const APP = express()

// =================================================================================================
// CONFIGURATIONS
// =================================================================================================

APP.set('view engine', 'ejs')

// =================================================================================================
// MIDDLEWARE
// =================================================================================================

APP.use(logger('dev'))
APP.use(session({
    secret: process.env.SESSION_SECRET,
    resave: false,
    saveUninitialized: true,
    cookie: { maxAge: 1000 * 60 * 60 * TIMEOUT_HOURS } 
}))
APP.use(flash())
APP.use(express.json())
APP.use(express.urlencoded({ extended: true }))
APP.use(passport.initialize())
APP.use(passport.session())
APP.use(express.static(__dirname + '/static'))

// Define any values that need to be used by EVERY res.render() call here as part of res.locals
// E.g., loggedIn is used in every .ejs by the header to see if the user is logged in to display the profile icon
APP.use((req, res, next) => {
    res.locals.user = {}
    res.locals.user.isLoggedIn = req.isAuthenticated()
    if (req.user) { // req.user is attached by passport, and populated with data from mongoose by passport-local-mongoose (e.g., req.user.DOCUMENT_ATTRIBUTE)
        
    }
    next()
})

passport.use(Account.createStrategy())
passport.serializeUser(Account.serializeUser())
passport.deserializeUser(Account.deserializeUser())


// =================================================================================================
// ROUTING
// =================================================================================================

// GET

// Authorized-only pages
APP.get('/a/:authorized_only_page', ensureLoggedIn(), (req, res) => {
    res.render(`authorized/${authorized_only_page}`, { userInfo: req.user }, (err, html) => {
        if (err) return next(err)
        else res.status(200).send(html)
    })
})

// Redirect default to homepage
APP.get('/', (req, res, next) => {
    res.redirect('/home')
})

// Publicly-reachable pages (i.e., no login required)
APP.get('/:static_page', (req, res, next) => {
    res.render(`public/${req.params.static_page}`, (err, html) => {
        if (err) return next(err)
        else res.status(200).send(html)
    })
})

// POST

// Register new user
APP.post('/register', (req, res, next) => {
    console.log(req.body.username, req.body.email)
    Account.register(new Account({ username: req.body.username, email: req.body.email }), req.body.password, (err) => {
        if (err) return next(err)
        else res.redirect('/registration-success')
    })
})

// Save profile settings
APP.post('/save', ensureLoggedIn(), (req, res, next) => {
    Account.findById(req.user._id, (err, user) => {
        if (err) return next(err)
        user.save().then(_ => {
            res.redirect('/profile')
            res.end()
        })
    })
})

// Log in to existing user
APP.post('/login', passport.authenticate('local', { 
    successRedirect: '/login-success',
    failureRedirect: '/login',
    failureFlash: true
}))

// Log out from logged in user
APP.post('/logout', ensureLoggedIn(), (req, res, next) => {
    req.logout( (err) => {
        if (err) return next(err)
        else res.redirect('/')
    })
})

// =================================================================================================
// ERROR HANDLING
// =================================================================================================

// Client-side errors (generated by req.xhr)
const clientErrorHandler = function(err, req, res, next) {
    // Handling missing page from ejs (God why can't they just make an error type that extends error...)
    if (err.message.includes('Failed to lookup view')) { err.status = 404 }
    // No clue what this error is
    else if (req.xhr) { err.status = 500 }
    return next(err)
}

// Catch server-side errors (e.g., ReferenceError)
const serverErrorHandler = function(err, req, res, next) {
    if (err instanceof ReferenceError) {
        err.status = 500
    }
    return next(err)
}

// Catch-all error handler to render error pages
const errorHandler = function(err, req, res, next) {
    console.log(err)
    res.status(err.status || 500)
    res.render('public/error', {
        code: res.statusCode
    })
}

APP.use(clientErrorHandler)
APP.use(serverErrorHandler)
APP.use(errorHandler)

// =================================================================================================
// STARTUP
// =================================================================================================

var listener = APP.listen(process.env.PORT || 8080, () => {
    console.log(`Listening on port ${listener.address().port}`)
})

module.exports.app = APP

